// <auto-generated />
using System;
using Blog.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Application.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260110183155_BlogFirstMigrations")]
    partial class BlogFirstMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ef")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Application.Models.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("About", "blg");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admin", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 15, 5, 18, 59, 976, DateTimeKind.Local).AddTicks(3459),
                            Password = "sG7p18vO",
                            UserName = "Anil56"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 6, 8, 50, 32, 714, DateTimeKind.Local).AddTicks(8097),
                            Password = "n2fd9Wu1",
                            UserName = "Bulan.Aclan"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 11, 13, 39, 45, 974, DateTimeKind.Local).AddTicks(2211),
                            Password = "R2pY1fcv",
                            UserName = "Baykal.Yildirim83"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("AdminsId")
                        .HasColumnType("int");

                    b.Property<string>("BlogImage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminsId");

                    b.ToTable("Blog", "blg");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentSubject")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MembersId");

                    b.ToTable("Comment", "blg");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Communication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Communication", "blg");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstame")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Members", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "34",
                            CreatedDate = new DateTime(2025, 6, 14, 21, 55, 38, 55, DateTimeKind.Local).AddTicks(307),
                            Email = "Baymunke.Sinanoglu88@hotmail.com",
                            Firstame = "Bulmuş",
                            LastName = "Barbarosoğlu",
                            PassWord = "EKT1tm6QYr",
                            PhoneNumber = 2802150
                        },
                        new
                        {
                            Id = 2,
                            Age = "53",
                            CreatedDate = new DateTime(2025, 10, 3, 0, 43, 57, 845, DateTimeKind.Local).AddTicks(7745),
                            Email = "Alpertunga_Velioglu@gmail.com",
                            Firstame = "Aladoğan",
                            LastName = "Aclan",
                            PassWord = "pzCyvMv_G5",
                            PhoneNumber = 4793339
                        },
                        new
                        {
                            Id = 3,
                            Age = "23",
                            CreatedDate = new DateTime(2025, 5, 5, 5, 5, 16, 856, DateTimeKind.Local).AddTicks(5267),
                            Email = "Baldu78@yahoo.com",
                            Firstame = "Işığ",
                            LastName = "Ertepınar",
                            PassWord = "oCf3y6SDt0",
                            PhoneNumber = 1771156
                        },
                        new
                        {
                            Id = 4,
                            Age = "58",
                            CreatedDate = new DateTime(2025, 4, 21, 14, 49, 34, 941, DateTimeKind.Local).AddTicks(2220),
                            Email = "Barlibay_Akgul60@hotmail.com",
                            Firstame = "Beçkem",
                            LastName = "Pektemek",
                            PassWord = "kUbr1_BjNS",
                            PhoneNumber = 7835622
                        },
                        new
                        {
                            Id = 5,
                            Age = "29",
                            CreatedDate = new DateTime(2025, 12, 31, 16, 0, 22, 59, DateTimeKind.Local).AddTicks(5408),
                            Email = "Dururbunsuz62@hotmail.com",
                            Firstame = "Ceyhun",
                            LastName = "Çatalbaş",
                            PassWord = "aZczRi5KTr",
                            PhoneNumber = 9225076
                        },
                        new
                        {
                            Id = 6,
                            Age = "64",
                            CreatedDate = new DateTime(2025, 3, 5, 0, 15, 33, 635, DateTimeKind.Local).AddTicks(2379),
                            Email = "Beg39@yahoo.com",
                            Firstame = "Bozkurt",
                            LastName = "Çetiner",
                            PassWord = "Ns_LYNToqa",
                            PhoneNumber = 9122321
                        },
                        new
                        {
                            Id = 7,
                            Age = "49",
                            CreatedDate = new DateTime(2025, 3, 8, 15, 40, 36, 377, DateTimeKind.Local).AddTicks(5284),
                            Email = "Alpbilge.Tekelioglu88@yahoo.com",
                            Firstame = "Bulut",
                            LastName = "Yalçın",
                            PassWord = "ondrJeTbaP",
                            PhoneNumber = 3475922
                        },
                        new
                        {
                            Id = 8,
                            Age = "49",
                            CreatedDate = new DateTime(2025, 5, 12, 14, 44, 1, 110, DateTimeKind.Local).AddTicks(9450),
                            Email = "Balkik93@gmail.com",
                            Firstame = "Etil",
                            LastName = "Tunçeri",
                            PassWord = "IYk7dVLj8I",
                            PhoneNumber = 2233570
                        },
                        new
                        {
                            Id = 9,
                            Age = "45",
                            CreatedDate = new DateTime(2025, 11, 8, 20, 4, 55, 35, DateTimeKind.Local).AddTicks(8489),
                            Email = "Azban.Daglaroglu@gmail.com",
                            Firstame = "Aşan",
                            LastName = "Çetin",
                            PassWord = "SypE3B2R9P",
                            PhoneNumber = 5697001
                        },
                        new
                        {
                            Id = 10,
                            Age = "35",
                            CreatedDate = new DateTime(2025, 12, 21, 14, 7, 16, 163, DateTimeKind.Local).AddTicks(7678),
                            Email = "Adli.Cagiran@gmail.com",
                            Firstame = "Alparslan",
                            LastName = "Tazegül",
                            PassWord = "AVO3xqtRoe",
                            PhoneNumber = 3692632
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.HasOne("Blog.Application.Models.Entities.Admins", "Admins")
                        .WithMany("Blogs")
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Comments", b =>
                {
                    b.HasOne("Blog.Application.Models.Entities.Members", "Members")
                        .WithMany("Comments")
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Members", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
