// <auto-generated />
using System;
using Blog.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Application.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260119152125_update_app_userNew")]
    partial class update_app_userNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blg")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Application.Models.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("About", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 19, 16, 50, 2, 66, DateTimeKind.Local).AddTicks(6437),
                            Description = "Patlıcan telefonu quis ullam vitae masaya alias kulu duyulmamış voluptate. Gül çarpan ea architecto labore dolorem hesap. Ona koştum aperiam telefonu ama praesentium neque.\n\nReprehenderit dolayı sıradanlıktan. Olduğu neque çorba quis sarmal. Aliquam çobanın dignissimos aliquam ducimus suscipit cezbelendi adipisci gazete. İllo de eius dolayı voluptate şafak magnam doloremque esse reprehenderit. Quia olduğu illo quam quasi modi.",
                            FotoUrl = "https://picsum.photos/640/480/?image=317"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admin", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 16, 11, 27, 11, 61, DateTimeKind.Local).AddTicks(2307),
                            Password = "8A8Qdyyzu0",
                            UserName = "Bilgetamgaci.Agaoglu79"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 30, 21, 13, 9, 884, DateTimeKind.Local).AddTicks(4264),
                            Password = "AvMxbOyqHp",
                            UserName = "Bakir.Suleymanoglu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 26, 17, 3, 6, 205, DateTimeKind.Local).AddTicks(3982),
                            Password = "12vrp8VHlO",
                            UserName = "Ayma_Tuzun16"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("BlogImage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Blog", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 2,
                            BlogImage = "https://picsum.photos/640/480/?image=795",
                            CreatedDate = new DateTime(2026, 1, 15, 10, 36, 24, 51, DateTimeKind.Local).AddTicks(2936),
                            Description = "Qui telefonu dicta voluptas kutusu ekşili consectetur nemo illo vel. Eum gül voluptatem quia totam quia odio. Nihil sayfası sayfası dolores quia voluptatem eaque iure lakin. Labore voluptatem praesentium açılmadan.\n\nDergi aspernatur sed. İnventore eaque iusto gülüyorum quasi patlıcan beğendim balıkhaneye tv. Karşıdakine ki corporis vitae dolayı non sequi ipsa. Kulu sunt ki gördüm vel dolayı nostrum gülüyorum sevindi dolayı.\n\nVeritatis değerli eve aperiam aut camisi ama. Nemo sequi ışık sarmal fugit beatae çarpan sequi salladı umut. Mi kalemi nisi doğru koşuyorlar ki qui laudantium ut aliquid. Açılmadan sıla voluptatem nesciunt vitae.",
                            Title = "Alias quis et et ullam."
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=263",
                            CreatedDate = new DateTime(2026, 1, 10, 17, 42, 21, 648, DateTimeKind.Local).AddTicks(2839),
                            Description = "Makinesi telefonu et doloremque eius aut voluptatem kulu. Şafak biber lambadaki labore nesciunt dışarı. Koyun ex de otobüs.\n\nMasaya labore inventore numquam gülüyorum batarya. Göze mi duyulmamış velit ratione labore sandalye koyun quia. Quia kulu exercitationem eos. Doloremque dolorem hesap orta adipisci için qui. Kalemi dergi aut ullam için kulu.\n\nVeniam ea qui filmini ışık. Fugit ut sed aspernatur. Eius eaque ipsa perferendis ipsam minima filmini ışık gitti dağılımı. İpsa orta sıla anlamsız filmini. İllo voluptatem sıradanlıktan quasi yapacakmış mutlu. Aliquid göze neque consequuntur eos çorba sit.",
                            Title = "Praesentium ad masanın veritatis filmini."
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=317",
                            CreatedDate = new DateTime(2026, 1, 11, 17, 25, 5, 302, DateTimeKind.Local).AddTicks(1233),
                            Description = "Tempora okuma ad sit consequuntur aut sevindi gördüm. Architecto adresini kulu adresini tempora dergi. Eve gidecekmiş otobüs oldular. Consectetur enim fugit non hesap. Dolorem çıktılar ea aut odio filmini balıkhaneye ışık nostrum.\n\nConsequatur suscipit consequuntur masaya. Consequatur çobanın amet ve dolor ut. Sayfası sunt layıkıyla totam okuma nihil ut. Sayfası değirmeni filmini ducimus incidunt nesciunt consequuntur et laudantium. Bilgiyasayarı lambadaki corporis ekşili. Domates çünkü ona beatae aut gazete et.\n\nUt dolore dolorem. Değirmeni nesciunt okuma sokaklarda layıkıyla ut cesurca okuma. Sunt numquam göze rem de ratione voluptatem duyulmamış kapının quae. Voluptate iusto consequatur sarmal ullam dicta adanaya.",
                            Title = "Quia vitae şafak magnam nesciunt."
                        },
                        new
                        {
                            Id = 4,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=60",
                            CreatedDate = new DateTime(2026, 1, 5, 6, 22, 18, 523, DateTimeKind.Local).AddTicks(1487),
                            Description = "Ona dignissimos sinema corporis non olduğu sit ötekinden. Voluptatum aspernatur eius nostrum sarmal totam dolor. De aperiam voluptate quis reprehenderit dergi in.\n\nSayfası kutusu tempora fugit. Nemo göze corporis magni fugit consequatur iure sarmal eaque consequatur. Olduğu hesap aperiam mıknatıslı çobanın. Cesurca gördüm enim laudantium değerli.\n\nKoştum sed domates ut qui balıkhaneye incidunt. Bilgiyasayarı eaque sarmal ki. Consequatur sit ekşili duyulmamış voluptatem sıfat deleniti telefonu dolorem. Neque explicabo eos aut sevindi anlamsız qui amet aperiam non. Teldeki autem eius sinema eum göze.",
                            Title = "Adresini dergi çıktılar anlamsız quia."
                        },
                        new
                        {
                            Id = 5,
                            AdminId = 3,
                            BlogImage = "https://picsum.photos/640/480/?image=210",
                            CreatedDate = new DateTime(2026, 1, 1, 12, 45, 17, 630, DateTimeKind.Local).AddTicks(5304),
                            Description = "Açılmadan magni ducimus teldeki çorba quaerat velit ut karşıdakine aut. Şafak sinema illo ad eve consequatur. Koşuyorlar adresini dolore ducimus rem. İpsum suscipit commodi sıradanlıktan. Mıknatıslı makinesi ducimus quia deleniti inventore ve sinema.\n\nNihil totam balıkhaneye eius ona balıkhaneye oldular ab. Aliquid incidunt voluptatem patlıcan aut kapının vitae ışık. Mıknatıslı beatae otobüs aliquam kutusu explicabo un. Koşuyorlar inventore tempora labore salladı sayfası ducimus sed magni.\n\nKoşuyorlar masaya cezbelendi ut voluptatem. Vitae bilgiyasayarı salladı dergi filmini velit bilgisayarı quaerat gülüyorum düşünüyor. Non alias layıkıyla biber quis quia. Layıkıyla gidecekmiş batarya laboriosam aut.",
                            Title = "Labore için incidunt bundan anlamsız."
                        },
                        new
                        {
                            Id = 6,
                            AdminId = 2,
                            BlogImage = "https://picsum.photos/640/480/?image=489",
                            CreatedDate = new DateTime(2025, 12, 28, 7, 4, 40, 846, DateTimeKind.Local).AddTicks(7229),
                            Description = "Şafak ea ea nihil. Aut göze koşuyorlar et bilgisayarı. İllo sed et.\n\nSit dolor molestiae et. Odio alias gitti. Lakin yaptı enim consequatur mutlu doloremque türemiş autem türemiş. Ea lakin bilgisayarı. Lakin cesurca voluptatem.\n\nDucimus ut de çünkü ea aperiam aut. Veniam autem ona magni batarya. Kapının sarmal iusto. İncidunt laudantium deleniti aut. Ducimus çobanın consequatur ad esse kulu.",
                            Title = "Quam aliquam sinema deleniti consectetur."
                        },
                        new
                        {
                            Id = 7,
                            AdminId = 3,
                            BlogImage = "https://picsum.photos/640/480/?image=903",
                            CreatedDate = new DateTime(2026, 1, 12, 8, 40, 2, 749, DateTimeKind.Local).AddTicks(8904),
                            Description = "Enim hesap eos karşıdakine çobanın numquam ducimus koştum gülüyorum camisi. Dolayı magnam sequi veritatis. Ve odit ut patlıcan gördüm quia. Adresini otobüs olduğu sıradanlıktan. Neque balıkhaneye eve bahar consequatur. Quam yapacakmış mıknatıslı aperiam bilgiyasayarı ad sit.\n\nAmet doloremque illo eius quaerat dağılımı sıradanlıktan aliquam odio un. Exercitationem odit yaptı reprehenderit. Yaptı et çıktılar magnam duyulmamış ut minima. Ullam gitti magnam sinema telefonu kutusu enim. Non corporis doloremque sevindi sarmal ab. Makinesi mutlu un iusto.\n\nAperiam sit nemo türemiş adresini. Sıfat ducimus ipsam ki doloremque modi mıknatıslı quia. Suscipit yapacakmış oldular düşünüyor.",
                            Title = "Domates koştum veritatis modi oldular."
                        },
                        new
                        {
                            Id = 8,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=173",
                            CreatedDate = new DateTime(2026, 1, 3, 5, 10, 45, 326, DateTimeKind.Local).AddTicks(1661),
                            Description = "Eaque quia koyun sit quasi qui voluptatem değerli. Non sıfat teldeki accusantium reprehenderit velit camisi çobanın lakin voluptas. Mi sayfası umut alias dışarı vitae çorba fugit.\n\nNumquam architecto aliquam doloremque öyle quia suscipit. Quae salladı sayfası açılmadan salladı anlamsız salladı qui velit eos. Consequuntur dolore çorba otobüs teldeki ekşili adresini tv accusantium camisi. Türemiş karşıdakine olduğu orta dolorem lambadaki ea çıktılar mıknatıslı.\n\nİpsam sokaklarda blanditiis quis beatae. Quia filmini adanaya quasi batarya ipsum. Dergi ad beğendim velit. Sunt gidecekmiş veniam salladı ut çarpan et. Eve dolayı quam quis umut. Ut koştum ea.",
                            Title = "İnventore teldeki quaerat gidecekmiş velit."
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Communication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Communication", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 17, 14, 19, 39, 250, DateTimeKind.Local).AddTicks(1017),
                            Email = "Bornak_Elicin@gmail.com",
                            Message = "Enim voluptatem ipsam mi. Modi velit dolorem doloremque aspernatur sevindi in. Dolayı sıradanlıktan gül ötekinden enim gidecekmiş. Dolayı commodi velit voluptatum beğendim. Ducimus okuma voluptatem nostrum odio. Bundan koyun koştum.",
                            Name = "Bağaşatulu Sadıklar",
                            Subject = "Cezbelendi ama."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 15, 3, 44, 34, 537, DateTimeKind.Local).AddTicks(6234),
                            Email = "Babir_Arican@yahoo.com",
                            Message = "Consequuntur eaque praesentium doloremque teldeki ama deleniti. Nesciunt voluptatem otobüs alias. Quae adresini duyulmamış suscipit velit dolor labore sed sıradanlıktan tempora.",
                            Name = "Altan Babaoğlu",
                            Subject = "Nemo sit."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 18, 6, 16, 19, 457, DateTimeKind.Local).AddTicks(3270),
                            Email = "Alaboru.Ertepinar@gmail.com",
                            Message = "Çorba gazete sarmal cezbelendi eum çıktılar. Quis odit quia ve in layıkıyla magnam quae. Dağılımı enim sandalye makinesi. Ad sequi consectetur bahar quia ea quaerat.",
                            Name = "Aygırak Saygıner",
                            Subject = "Labore quis."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 18, 19, 16, 40, 224, DateTimeKind.Local).AddTicks(1935),
                            Email = "Guvercin52@yahoo.com",
                            Message = "Gidecekmiş voluptatem velit. Filmini nisi totam veritatis labore sarmal. Filmini de consectetur beatae nostrum velit çorba sokaklarda dicta. Consequatur kulu sit ve sunt un quia.",
                            Name = "Adlıbeğ Kıraç ",
                            Subject = "Lakin filmini."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 18, 15, 19, 46, 294, DateTimeKind.Local).AddTicks(961),
                            Email = "Ertenozuk_Tekelioglu86@gmail.com",
                            Message = "Çobanın consequatur eius sandalye quia quaerat. Magni nemo gül sıla. Düşünüyor labore gitti çarpan iure öyle ex autem odio. Dağılımı exercitationem dignissimos incidunt voluptatem. Sinema dolor veritatis kapının lambadaki gitti bilgiyasayarı patlıcan.",
                            Name = "Buğday Karaduman",
                            Subject = "Magnam umut."
                        });
                });

            modelBuilder.Entity("Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int?>("BlogsId")
                        .HasColumnType("int");

                    b.Property<string>("CommentSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AppUserId1");

                    b.HasIndex("BlogId");

                    b.HasIndex("BlogsId");

                    b.ToTable("Comments", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 7,
                            CommentSubject = "Un alias consectetur.",
                            CommentText = "enim",
                            CreatedDate = new DateTime(2026, 1, 12, 12, 36, 45, 76, DateTimeKind.Local).AddTicks(3602),
                            Email = "Isik.Ozdogan@hotmail.com",
                            Name = "Buluç Baturalp"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "73d21eb2-7468-42f6-ba85-f2045d269c03",
                            BlogId = 1,
                            CommentSubject = "Ea gülüyorum aliquam.",
                            CommentText = "layıkıyla",
                            CreatedDate = new DateTime(2026, 1, 12, 20, 25, 21, 218, DateTimeKind.Local).AddTicks(2366),
                            Email = "Isik.Alyanak@yahoo.com",
                            Name = "Gülegen Uluhan"
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            CommentSubject = "Exercitationem dolore ab.",
                            CommentText = "eum",
                            CreatedDate = new DateTime(2026, 1, 17, 5, 14, 52, 11, DateTimeKind.Local).AddTicks(787),
                            Email = "Algu.Ozansoy@gmail.com",
                            Name = "Alptuğrul Uluhan"
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 2,
                            CommentSubject = "Quia veritatis blanditiis.",
                            CommentText = "Amet veritatis balıkhaneye layıkıyla quaerat tempora voluptate odit uzattı.",
                            CreatedDate = new DateTime(2026, 1, 13, 18, 15, 38, 81, DateTimeKind.Local).AddTicks(167),
                            Email = "Bagaturcigsi_Mayhos17@yahoo.com",
                            Name = "Günçiçek Özdenak"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = "ff719141-9016-4f96-a8ee-8a7783928650",
                            BlogId = 5,
                            CommentSubject = "Hesap makinesi ışık.",
                            CommentText = "Batarya quae çorba ea.",
                            CreatedDate = new DateTime(2026, 1, 16, 23, 35, 45, 881, DateTimeKind.Local).AddTicks(967),
                            Email = "Erten29@hotmail.com",
                            Name = "Bangu Özkök "
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 5,
                            CommentSubject = "Gördüm ama dolores.",
                            CommentText = "Mi qui masaya voluptatem ipsam türemiş totam ducimus. Koşuyorlar voluptate alias molestiae balıkhaneye. Odio ad patlıcan. Karşıdakine consequatur velit laudantium beğendim adanaya çıktılar voluptatem doloremque. Oldular düşünüyor blanditiis dignissimos magni aspernatur voluptate dicta. Voluptatem consequatur domates sayfası voluptatem laudantium consequatur dağılımı.",
                            CreatedDate = new DateTime(2026, 1, 12, 19, 58, 1, 295, DateTimeKind.Local).AddTicks(1948),
                            Email = "Ala40@gmail.com",
                            Name = "Altankağan Bakırcıoğlu"
                        },
                        new
                        {
                            Id = 7,
                            BlogId = 2,
                            CommentSubject = "Camisi aspernatur türemiş.",
                            CommentText = "beğendim",
                            CreatedDate = new DateTime(2026, 1, 12, 6, 10, 32, 798, DateTimeKind.Local).AddTicks(9260),
                            Email = "Aybars.Arican@yahoo.com",
                            Name = "Adık Tütüncü"
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = "73d21eb2-7468-42f6-ba85-f2045d269c03",
                            BlogId = 1,
                            CommentSubject = "Alias sarmal voluptatem.",
                            CommentText = "Göze bilgisayarı quia vel qui nemo kapının ut incidunt explicabo.",
                            CreatedDate = new DateTime(2026, 1, 15, 10, 55, 48, 493, DateTimeKind.Local).AddTicks(379),
                            Email = "Bolmus_Basoglu32@hotmail.com",
                            Name = "Adalan Akgül"
                        },
                        new
                        {
                            Id = 9,
                            BlogId = 7,
                            CommentSubject = "Eius yapacakmış reprehenderit.",
                            CommentText = "Explicabo dolayı salladı orta koyun dicta beatae aut.",
                            CreatedDate = new DateTime(2026, 1, 18, 20, 43, 53, 729, DateTimeKind.Local).AddTicks(7448),
                            Email = "Baykoca_Aybar60@hotmail.com",
                            Name = "Basat Keçeci"
                        },
                        new
                        {
                            Id = 10,
                            BlogId = 1,
                            CommentSubject = "Consequuntur de voluptatem.",
                            CommentText = "Autem iusto sarmal beatae aspernatur kulu.",
                            CreatedDate = new DateTime(2026, 1, 18, 12, 26, 28, 778, DateTimeKind.Local).AddTicks(5846),
                            Email = "Arnac8@yahoo.com",
                            Name = "Burkay Baykam"
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = "5a612e79-175a-487b-98e7-5ea2ba2c23e9",
                            BlogId = 8,
                            CommentSubject = "Voluptate architecto aperiam.",
                            CommentText = "açılmadan",
                            CreatedDate = new DateTime(2026, 1, 16, 3, 22, 3, 308, DateTimeKind.Local).AddTicks(4466),
                            Email = "Bolsun.Erberk73@hotmail.com",
                            Name = "Benlidemir Özberk"
                        },
                        new
                        {
                            Id = 12,
                            AppUserId = "391effa3-4115-422c-a8a1-1a3b85331cac",
                            BlogId = 5,
                            CommentSubject = "Minima numquam sed.",
                            CommentText = "Kutusu değerli consequatur exercitationem bahar suscipit laudantium in. Eius amet telefonu magnam. Qui mutlu esse gül değirmeni vel velit inventore qui. İpsum qui eos quis quae modi molestiae değerli.",
                            CreatedDate = new DateTime(2026, 1, 10, 15, 28, 14, 831, DateTimeKind.Local).AddTicks(7651),
                            Email = "Baykoca.Orbay@yahoo.com",
                            Name = "Beğ Gönültaş"
                        },
                        new
                        {
                            Id = 13,
                            AppUserId = "5a612e79-175a-487b-98e7-5ea2ba2c23e9",
                            BlogId = 6,
                            CommentSubject = "Ut dağılımı tempora.",
                            CommentText = "Gül dolorem amet. Teldeki masanın voluptatum kalemi exercitationem molestiae sıfat umut. Consectetur layıkıyla ut blanditiis mutlu quam. Mutlu ab qui aut domates consectetur numquam koştum. Aliquid türemiş quia enim incidunt lakin ea blanditiis kulu. Et çarpan ut eos ab dolore explicabo labore sit quasi.",
                            CreatedDate = new DateTime(2026, 1, 18, 8, 36, 18, 907, DateTimeKind.Local).AddTicks(2179),
                            Email = "Borlukcu.Corekci@yahoo.com",
                            Name = "Aktan Elçiboğa"
                        },
                        new
                        {
                            Id = 14,
                            BlogId = 2,
                            CommentSubject = "Ratione mutlu sunt.",
                            CommentText = "Reprehenderit salladı eius gidecekmiş domates.",
                            CreatedDate = new DateTime(2026, 1, 10, 16, 3, 4, 92, DateTimeKind.Local).AddTicks(1010),
                            Email = "Adli28@hotmail.com",
                            Name = "Boyankulu Yıldırım "
                        },
                        new
                        {
                            Id = 15,
                            AppUserId = "ff719141-9016-4f96-a8ee-8a7783928650",
                            BlogId = 2,
                            CommentSubject = "Reprehenderit umut gördüm.",
                            CommentText = "Fugit koyun cesurca çünkü. İnventore koştum ea laboriosam beğendim. Aliquam molestiae quia kapının patlıcan praesentium. Çarpan masaya eve sed uzattı odit orta biber consequatur aut. Numquam ducimus ex koşuyorlar esse.",
                            CreatedDate = new DateTime(2026, 1, 17, 9, 42, 16, 51, DateTimeKind.Local).AddTicks(7390),
                            Email = "Boga_Tekelioglu@hotmail.com",
                            Name = "Aşanboğa Dağdaş"
                        },
                        new
                        {
                            Id = 16,
                            AppUserId = "ec8ca8dd-10e7-46f0-8cb7-fc62a4803a22",
                            BlogId = 3,
                            CommentSubject = "Dignissimos commodi ışık.",
                            CommentText = "Doğru gitti autem kulu domates balıkhaneye eos illo adanaya.\nDışarı et commodi iure incidunt.\nAmet dolayı sequi otobüs aut kalemi cezbelendi aut de.",
                            CreatedDate = new DateTime(2026, 1, 17, 13, 58, 10, 94, DateTimeKind.Local).AddTicks(7184),
                            Email = "Bokde38@gmail.com",
                            Name = "Burunduk Süleymanoğlu"
                        },
                        new
                        {
                            Id = 17,
                            BlogId = 6,
                            CommentSubject = "Kapının aperiam perferendis.",
                            CommentText = "Fugit numquam gitti sevindi. Exercitationem vel aliquid corporis quis rem aliquid illo eum. Consequatur velit iure sıradanlıktan yazın koşuyorlar bundan beğendim aperiam sıradanlıktan. Kalemi in ekşili incidunt dolorem öyle kutusu reprehenderit.",
                            CreatedDate = new DateTime(2026, 1, 19, 10, 17, 45, 393, DateTimeKind.Local).AddTicks(9798),
                            Email = "Belgi4@gmail.com",
                            Name = "Artukaç Öztonga"
                        },
                        new
                        {
                            Id = 18,
                            BlogId = 7,
                            CommentSubject = "Consequuntur çorba un.",
                            CommentText = "İure ea qui quaerat kutusu un iure cesurca değerli.",
                            CreatedDate = new DateTime(2026, 1, 11, 11, 21, 14, 656, DateTimeKind.Local).AddTicks(7036),
                            Email = "Edil_Yilmazer@hotmail.com",
                            Name = "Baykal Erez"
                        },
                        new
                        {
                            Id = 19,
                            AppUserId = "73d21eb2-7468-42f6-ba85-f2045d269c03",
                            BlogId = 3,
                            CommentSubject = "Adipisci açılmadan lakin.",
                            CommentText = "Veritatis laudantium türemiş yazın koştum sit uzattı.\nDoğru consectetur sıla filmini masaya ipsam koştum anlamsız değirmeni.\nVoluptate düşünüyor ekşili corporis nemo adresini nesciunt.\nAut ad reprehenderit.\nSequi telefonu balıkhaneye.",
                            CreatedDate = new DateTime(2026, 1, 10, 4, 14, 34, 911, DateTimeKind.Local).AddTicks(5910),
                            Email = "Arik_Atan55@hotmail.com",
                            Name = "Benlidemir Koç"
                        },
                        new
                        {
                            Id = 20,
                            BlogId = 7,
                            CommentSubject = "Gazete quam sıla.",
                            CommentText = "Laboriosam velit gitti qui. Umut çobanın çünkü quis gülüyorum lambadaki ea. Ona gördüm labore kutusu inventore magni oldular. Numquam ipsam neque koşuyorlar kutusu ipsam quaerat un. Uzattı olduğu enim nihil. Beğendim sit çakıl consequuntur.",
                            CreatedDate = new DateTime(2026, 1, 12, 22, 2, 30, 632, DateTimeKind.Local).AddTicks(7173),
                            Email = "Amac_Yesilkaya@yahoo.com",
                            Name = "Ergene Yalçın"
                        },
                        new
                        {
                            Id = 21,
                            BlogId = 1,
                            CommentSubject = "Masanın aut sıfat.",
                            CommentText = "Quia değirmeni voluptatum masanın labore. Aut sit çorba sevindi eius ducimus duyulmamış vitae blanditiis dolor. Dergi voluptatem değirmeni koşuyorlar sed gül patlıcan.",
                            CreatedDate = new DateTime(2026, 1, 16, 21, 37, 20, 388, DateTimeKind.Local).AddTicks(146),
                            Email = "Bayruk18@hotmail.com",
                            Name = "Azban Mertoğlu"
                        },
                        new
                        {
                            Id = 22,
                            BlogId = 3,
                            CommentSubject = "Commodi sıla dergi.",
                            CommentText = "Koyun laudantium numquam quam quis. Patlıcan lakin salladı türemiş perferendis balıkhaneye suscipit dolor dicta iusto. Balıkhaneye değirmeni consectetur. Totam nisi sit iure aut adanaya. Consequuntur düşünüyor sayfası gül uzattı ama vitae. Deleniti gülüyorum nisi nostrum magnam architecto sarmal quis cesurca.",
                            CreatedDate = new DateTime(2026, 1, 13, 6, 42, 37, 93, DateTimeKind.Local).AddTicks(6328),
                            Email = "Badruk_Ozkara@yahoo.com",
                            Name = "Iyıktağ Nalbantoğlu"
                        },
                        new
                        {
                            Id = 23,
                            AppUserId = "5a612e79-175a-487b-98e7-5ea2ba2c23e9",
                            BlogId = 2,
                            CommentSubject = "Consequatur aliquam gül.",
                            CommentText = "Ama okuma in gazete. Değirmeni yapacakmış değerli quasi ipsa yazın gitti ut duyulmamış sıfat. Quia değerli nemo.",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 40, 58, 50, DateTimeKind.Local).AddTicks(3278),
                            Email = "Budak.Dusenkalkar53@yahoo.com",
                            Name = "Atıkutlu Kuday"
                        },
                        new
                        {
                            Id = 24,
                            BlogId = 4,
                            CommentSubject = "Otobüs magni sandalye.",
                            CommentText = "enim",
                            CreatedDate = new DateTime(2026, 1, 17, 10, 51, 55, 844, DateTimeKind.Local).AddTicks(2136),
                            Email = "Akata87@gmail.com",
                            Name = "Barsgan Aykaç"
                        },
                        new
                        {
                            Id = 25,
                            BlogId = 6,
                            CommentSubject = "Ötekinden düşünüyor sıradanlıktan.",
                            CommentText = "Ama ab odit.\nKoştum ki amet.\nYapacakmış deleniti camisi.\nExercitationem gazete praesentium.",
                            CreatedDate = new DateTime(2026, 1, 10, 21, 5, 49, 691, DateTimeKind.Local).AddTicks(3466),
                            Email = "Arbay_Cagiran@hotmail.com",
                            Name = "Baksı Yıldızoğlu"
                        });
                });

            modelBuilder.Entity("EFIndentityDemo.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", "blg");

                    b.HasData(
                        new
                        {
                            Id = "ec8ca8dd-10e7-46f0-8cb7-fc62a4803a22",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1986, 7, 22, 16, 2, 15, 177, DateTimeKind.Local).AddTicks(8530),
                            City = "İstanbul",
                            ConcurrencyStamp = "0fc9acb1-4219-4481-967e-b60c1db91893",
                            Email = "Barcadogmus.Sayginer87@gmail.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BARCADOGMUS.SAYGINER87@GMAIL.COM",
                            NormalizedUserName = "BOKE_OZTUNA49",
                            PasswordHash = "AQAAAAIAAYagAAAAEAzQcDgFbCDFa7SS9NmrSMM2Roq1N4osiHbaY2XQhKymKBaz2ofuJFyQYTsVe53qhQ==",
                            PhoneNumber = "05850749644",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=218",
                            SecurityStamp = "8f72c925-e596-40a8-af99-3e00d064a30b",
                            TwoFactorEnabled = false,
                            UserName = "Boke_Oztuna49"
                        },
                        new
                        {
                            Id = "1390ab75-53f6-4bd5-840c-d1076be93c8c",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1984, 2, 16, 15, 18, 55, 124, DateTimeKind.Local).AddTicks(1722),
                            City = "Manisa",
                            ConcurrencyStamp = "7eaddf16-db20-4ae5-a8ba-0f0387131e0f",
                            Email = "Bulug15@hotmail.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BULUG15@HOTMAIL.COM",
                            NormalizedUserName = "BURULDAY24",
                            PasswordHash = "AQAAAAIAAYagAAAAEG+eqyXr+jOpudUr5RlMVBQyYJ+OomwGRAHIazkyUXGJiQnO90wT2iezQfURYux3tg==",
                            PhoneNumber = "05949433900",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=1060",
                            SecurityStamp = "5722844d-c038-4a92-8be6-8d7c4e0d9142",
                            TwoFactorEnabled = false,
                            UserName = "Burulday24"
                        },
                        new
                        {
                            Id = "40b1e082-0363-43c4-8a81-5ea90ddbb2ed",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2003, 5, 3, 23, 10, 49, 125, DateTimeKind.Local).AddTicks(8298),
                            City = "Düzce",
                            ConcurrencyStamp = "94faec8e-369f-4af7-9f59-54b728d718df",
                            Email = "Alaboru_Orbay@yahoo.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALABORU_ORBAY@YAHOO.COM",
                            NormalizedUserName = "BARSKAN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEDOR6NtST0WEivPiMVYshH0DirciH0RnmMXdmxO8raa/57WcHjrxCIRkf5EIlF8njQ==",
                            PhoneNumber = "05250715989",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=403",
                            SecurityStamp = "21db846b-5a8a-46ee-9bb2-70a9cd46e039",
                            TwoFactorEnabled = false,
                            UserName = "Barskan1"
                        },
                        new
                        {
                            Id = "a549638e-cd84-4307-94c6-e71ef200cdaa",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1998, 6, 5, 20, 28, 18, 814, DateTimeKind.Local).AddTicks(5300),
                            City = "Bayburt",
                            ConcurrencyStamp = "c27a67ee-bb16-4d63-b7e6-d8108e74d85c",
                            Email = "Bilig.Corekci36@gmail.com",
                            EmailConfirmed = true,
                            Gender = 2,
                            LockoutEnabled = false,
                            NormalizedEmail = "BILIG.COREKCI36@GMAIL.COM",
                            NormalizedUserName = "AYKURT_BALCI81",
                            PasswordHash = "AQAAAAIAAYagAAAAEFJjKjXoJcGx6tOupGgAijmv560OqoWbpt5HTz6rZYn2HUukgxNRSVtX2ANL67AicA==",
                            PhoneNumber = "05025303115",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=750",
                            SecurityStamp = "02f7c6ec-345e-485c-b9db-ebad96475b77",
                            TwoFactorEnabled = false,
                            UserName = "Aykurt_Balci81"
                        },
                        new
                        {
                            Id = "4226d55c-2a4b-43ec-82a6-e9d874cf0369",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1987, 7, 3, 13, 28, 42, 689, DateTimeKind.Local).AddTicks(9987),
                            City = "Bolu",
                            ConcurrencyStamp = "f2fbb9e4-67c5-4bb9-9fd7-3c29d8677906",
                            Email = "Bugubilge72@hotmail.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BUGUBILGE72@HOTMAIL.COM",
                            NormalizedUserName = "BAYINCUR3",
                            PasswordHash = "AQAAAAIAAYagAAAAELeAImKUqOjUs3su8vWM2om/63NdSJw1YSBAzIRzNUoFW0VicaYd4JBqgRvmEvn4ew==",
                            PhoneNumber = "05978758464",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=256",
                            SecurityStamp = "573ade9b-c32f-481a-b1d5-8ce4a5beedf4",
                            TwoFactorEnabled = false,
                            UserName = "Bayincur3"
                        },
                        new
                        {
                            Id = "e6859d6c-4eb0-4543-8e58-83404fc81aee",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1989, 9, 8, 13, 3, 15, 502, DateTimeKind.Local).AddTicks(385),
                            City = "Samsun",
                            ConcurrencyStamp = "79efb9ba-84e3-40a5-adac-a8ed9bfba8ed",
                            Email = "Barcadurmus_Sinanoglu@yahoo.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BARCADURMUS_SINANOGLU@YAHOO.COM",
                            NormalizedUserName = "BERENDEY.ERCETIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPyJTxB22pZg/5vLIXpuO9CUGyxLPt/VH22ubaPlcT8hV4bdVrOCIie9kgLNvv04Xw==",
                            PhoneNumber = "05469287152",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=690",
                            SecurityStamp = "57d11828-a9e5-4072-aa7b-6559eebbb09b",
                            TwoFactorEnabled = false,
                            UserName = "Berendey.Ercetin"
                        },
                        new
                        {
                            Id = "5a612e79-175a-487b-98e7-5ea2ba2c23e9",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1997, 10, 21, 4, 46, 55, 462, DateTimeKind.Local).AddTicks(3577),
                            City = "Samsun",
                            ConcurrencyStamp = "2188c88a-5583-423a-85e6-3e978c6bb083",
                            Email = "Barcadogdu.Dagdas25@gmail.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BARCADOGDU.DAGDAS25@GMAIL.COM",
                            NormalizedUserName = "BELGUC43",
                            PasswordHash = "AQAAAAIAAYagAAAAEGD9CxGlrqsE3/93FTscPJUD6E/RbNOjWb7F/7JlHsRhjat2Aspy5ONMHUGhJgOBAA==",
                            PhoneNumber = "05500367817",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=1068",
                            SecurityStamp = "e3874471-7dac-4d72-bab1-465752eb52c7",
                            TwoFactorEnabled = false,
                            UserName = "Belguc43"
                        },
                        new
                        {
                            Id = "ff719141-9016-4f96-a8ee-8a7783928650",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2006, 6, 13, 7, 2, 11, 704, DateTimeKind.Local).AddTicks(8361),
                            City = "Sakarya",
                            ConcurrencyStamp = "1f0e67a7-4f1d-40fa-9327-dd4fa3bc04a5",
                            Email = "Betemir_Okumus@yahoo.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BETEMIR_OKUMUS@YAHOO.COM",
                            NormalizedUserName = "BALTUR_ERKEKLI53",
                            PasswordHash = "AQAAAAIAAYagAAAAEGe6uftiJ0Kex/UbCvA713gD5sMNu0QA7KJb4LAY1OqPcT5Hunipk0YfTnPWZ3g6Cw==",
                            PhoneNumber = "05501320895",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=593",
                            SecurityStamp = "4c3cce98-9378-4a41-af78-b4b81f1477c3",
                            TwoFactorEnabled = false,
                            UserName = "Baltur_Erkekli53"
                        },
                        new
                        {
                            Id = "391effa3-4115-422c-a8a1-1a3b85331cac",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1996, 9, 24, 21, 52, 31, 619, DateTimeKind.Local).AddTicks(4861),
                            City = "Yalova",
                            ConcurrencyStamp = "08180c37-9176-40ae-a45e-53915afec7db",
                            Email = "Basat32@hotmail.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "BASAT32@HOTMAIL.COM",
                            NormalizedUserName = "ALPAGUT97",
                            PasswordHash = "AQAAAAIAAYagAAAAEGyX1+tQOD/sVnj2bvct1XGcUV3Uv11V6BpuJogtj9Ue8kpWGMSkJBYdb7Ac3aZT9A==",
                            PhoneNumber = "05120953195",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=355",
                            SecurityStamp = "1d111fa3-96b8-4822-8b16-9dc69545c05e",
                            TwoFactorEnabled = false,
                            UserName = "Alpagut97"
                        },
                        new
                        {
                            Id = "73d21eb2-7468-42f6-ba85-f2045d269c03",
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1980, 3, 10, 19, 12, 4, 585, DateTimeKind.Local).AddTicks(8949),
                            City = "K.maraş",
                            ConcurrencyStamp = "4133ea74-b1d2-44ba-a996-dc8cc71ae484",
                            Email = "Isilay0@yahoo.com",
                            EmailConfirmed = true,
                            Gender = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "ISILAY0@YAHOO.COM",
                            NormalizedUserName = "BUKTEGIN_HAKYEMEZ34",
                            PasswordHash = "AQAAAAIAAYagAAAAECSGIN+jCJC3B/kN1obCVotPtgS0yphAlo2/5pkMsgGZD5huO7rAtfjPUJ9+QQp0XA==",
                            PhoneNumber = "05174501142",
                            PhoneNumberConfirmed = false,
                            Picture = "https://picsum.photos/640/480/?image=838",
                            SecurityStamp = "095b3e13-9be4-48da-b6d3-1d3416cfcfbe",
                            TwoFactorEnabled = false,
                            UserName = "Buktegin_Hakyemez34"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.HasOne("Blog.Application.Models.Entities.Admins", "Admins")
                        .WithMany("Blogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("Comments", b =>
                {
                    b.HasOne("EFIndentityDemo.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EFIndentityDemo.Models.AppUser", null)
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId1");

                    b.HasOne("Blog.Application.Models.Entities.Blogs", "Blogs")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Application.Models.Entities.Blogs", null)
                        .WithMany("Comments")
                        .HasForeignKey("BlogsId");

                    b.Navigation("AppUser");

                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EFIndentityDemo.Models.AppUser", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
