// <auto-generated />
using System;
using Blog.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Application.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20260110184831_BlogFirstMigrations2")]
    partial class BlogFirstMigrations2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("blg")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Application.Models.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("About", "blg");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admin", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 11, 19, 42, 14, 207, DateTimeKind.Local).AddTicks(9197),
                            Password = "Xs7GWxyi",
                            UserName = "Alpulug.Adal"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 30, 12, 35, 42, 637, DateTimeKind.Local).AddTicks(4807),
                            Password = "aUFdiDvX",
                            UserName = "Arsun_Ozansoy93"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 2, 14, 9, 35, 28, 502, DateTimeKind.Local).AddTicks(9479),
                            Password = "XTPwfgca",
                            UserName = "Bugduz.Evliyaoglu81"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("BlogImage")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Blog", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 2,
                            BlogImage = "https://picsum.photos/640/480/?image=336",
                            CreatedDate = new DateTime(2026, 1, 4, 12, 6, 1, 460, DateTimeKind.Local).AddTicks(5689),
                            Description = "Qui koyun makinesi totam amet ve eos filmini. Domates kulu bilgiyasayarı gördüm açılmadan. Sıla çorba perferendis. Bilgisayarı mıknatıslı sarmal umut corporis dolorem un.\n\nOlduğu sayfası cezbelendi illo kulu cezbelendi ipsam otobüs. Doloremque bundan deleniti architecto dolayı ducimus. Camisi non eos değirmeni ab gördüm çünkü.\n\nExplicabo laudantium yaptı. Perferendis sit düşünüyor ullam aut et blanditiis labore quis velit. Sed çıktılar ve yaptı dergi bilgiyasayarı. Duyulmamış corporis molestiae voluptas göze çıktılar nesciunt. Doloremque olduğu eos sinema beğendim. Sayfası koyun makinesi.",
                            Title = "Laudantium karşıdakine voluptate koşuyorlar de."
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 3,
                            BlogImage = "https://picsum.photos/640/480/?image=336",
                            CreatedDate = new DateTime(2025, 12, 27, 7, 51, 12, 707, DateTimeKind.Local).AddTicks(1770),
                            Description = "Quaerat otobüs biber quis aut. Nemo magnam quam salladı adanaya telefonu suscipit. Quam domates adipisci dignissimos nisi türemiş gidecekmiş ut sit.\n\nSevindi aliquid adanaya velit dolore sokaklarda gülüyorum. Çıktılar modi velit. Koştum öyle hesap ea. Tempora dolayı qui yazın yapacakmış.\n\nSalladı neque sevindi sunt kapının. Qui aliquam balıkhaneye gül. Sevindi hesap ducimus amet ona oldular koyun totam sequi. Çıktılar mutlu non voluptas ea sunt aspernatur ve voluptatem nostrum. Alias adanaya uzattı modi iure koşuyorlar aut.",
                            Title = "Dignissimos ea magnam voluptate aspernatur."
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=1053",
                            CreatedDate = new DateTime(2025, 12, 20, 11, 48, 16, 778, DateTimeKind.Local).AddTicks(6780),
                            Description = "Layıkıyla nemo adresini minima dolores. İure gitti çünkü eius çobanın eaque ipsum tv umut teldeki. Enim dolores fugit labore sarmal.\n\nRem makinesi voluptatem perferendis. Bilgisayarı ratione sit aperiam odio lambadaki mıknatıslı dışarı duyulmamış. Düşünüyor consectetur numquam kapının gazete layıkıyla nostrum dağılımı tv. Doloremque ratione odit. İllo aspernatur çakıl sevindi labore praesentium qui. Gazete hesap nihil accusantium voluptatem beğendim dolore.\n\nOdio aliquam quia dolore karşıdakine nesciunt qui değerli koşuyorlar. Sıfat ullam quis adresini deleniti fugit masanın. Ratione gülüyorum sıfat veritatis sokaklarda. Gül gitti suscipit. Göze sinema beğendim qui vitae odio gazete enim layıkıyla magni.",
                            Title = "Işık kutusu layıkıyla nostrum veritatis."
                        },
                        new
                        {
                            Id = 4,
                            AdminId = 1,
                            BlogImage = "https://picsum.photos/640/480/?image=985",
                            CreatedDate = new DateTime(2025, 12, 15, 9, 9, 59, 133, DateTimeKind.Local).AddTicks(9484),
                            Description = "Eaque sandalye doloremque. Laudantium ekşili ekşili quae salladı explicabo velit tv olduğu gidecekmiş. Sed gitti enim. Adanaya illo quaerat ducimus inventore.\n\nOdio adipisci ut qui teldeki değerli öyle anlamsız. Ut eaque çobanın qui açılmadan masanın kulu ışık. İpsa enim koşuyorlar ötekinden beatae kalemi adipisci. Ullam açılmadan lambadaki yapacakmış voluptatem architecto. Autem aut velit sarmal aliquid. Koyun sandalye ipsam mi beatae.\n\nŞafak sed nostrum adanaya. Dağılımı duyulmamış bilgisayarı modi. Teldeki kalemi sarmal alias voluptate consectetur velit. Ducimus gazete çünkü layıkıyla ducimus. Sıradanlıktan ötekinden alias ipsa teldeki dolayı masaya.",
                            Title = "Minima koşuyorlar masanın cezbelendi yazın."
                        },
                        new
                        {
                            Id = 5,
                            AdminId = 2,
                            BlogImage = "https://picsum.photos/640/480/?image=619",
                            CreatedDate = new DateTime(2025, 12, 15, 13, 34, 34, 398, DateTimeKind.Local).AddTicks(7462),
                            Description = "Sandalye için exercitationem ipsa minima in consequatur nihil teldeki. Veniam okuma uzattı orta. Kulu bundan değirmeni totam dolorem accusantium sevindi.\n\nMinima praesentium kulu amet kutusu et eve. Exercitationem masanın ipsum nesciunt ipsam adanaya layıkıyla dolor düşünüyor. Uzattı illo un.\n\nAperiam koştum vel kapının koyun. Patlıcan biber yazın odit hesap batarya. Gülüyorum sed dolorem gidecekmiş magni gül. Doloremque doloremque iusto.",
                            Title = "Ex yapacakmış quaerat velit duyulmamış."
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentSubject")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Comment", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentSubject = "Non açılmadan göze.",
                            CommentText = "rem",
                            CreatedDate = new DateTime(2026, 1, 3, 1, 16, 15, 255, DateTimeKind.Local).AddTicks(5477),
                            Email = "Belek.Ozbey@gmail.com",
                            MemberId = 8,
                            Name = "Kezlik Gümüşpala"
                        },
                        new
                        {
                            Id = 2,
                            CommentSubject = "Gidecekmiş quia reprehenderit.",
                            CommentText = "Aliquid sayfası filmini mutlu gitti ötekinden dolorem beatae ullam. Mi ki dağılımı doloremque mi değirmeni voluptatem tempora praesentium lambadaki. İnventore sayfası ona alias mi quia de. Karşıdakine layıkıyla ullam dolorem hesap magnam. Lakin sed kapının. Corporis ut velit vitae nesciunt yapacakmış çobanın gördüm.",
                            CreatedDate = new DateTime(2026, 1, 7, 5, 42, 59, 907, DateTimeKind.Local).AddTicks(6389),
                            Email = "Altintamgan.Dalkiran@gmail.com",
                            MemberId = 6,
                            Name = "Alptegin Tanrıkulu"
                        },
                        new
                        {
                            Id = 3,
                            CommentSubject = "Sandalye qui nemo.",
                            CommentText = "Gülüyorum quis makinesi enim.\nQuis blanditiis dicta masanın consequatur kalemi magni accusantium dolor ut.\nOldular gazete dolayı yaptı nisi.\nNumquam ut değirmeni sevindi.\nDicta ut dışarı.",
                            CreatedDate = new DateTime(2026, 1, 10, 4, 13, 0, 384, DateTimeKind.Local).AddTicks(8658),
                            Email = "Bonek_Balaban@gmail.com",
                            MemberId = 10,
                            Name = "Belgüc Körmükçü"
                        },
                        new
                        {
                            Id = 4,
                            CommentSubject = "Consequuntur sit ipsa.",
                            CommentText = "salladı",
                            CreatedDate = new DateTime(2026, 1, 4, 10, 49, 28, 478, DateTimeKind.Local).AddTicks(3403),
                            Email = "Bukaktutuk53@yahoo.com",
                            MemberId = 9,
                            Name = "Elkin Küçükler"
                        },
                        new
                        {
                            Id = 5,
                            CommentSubject = "Adresini gülüyorum consequatur.",
                            CommentText = "Ex dolor yaptı duyulmamış quam consequatur.\nUllam sıla masaya eius anlamsız aperiam.\nEnim cesurca kapının yaptı lakin.\nGidecekmiş deleniti makinesi fugit quia mi sit.",
                            CreatedDate = new DateTime(2026, 1, 3, 15, 45, 20, 531, DateTimeKind.Local).AddTicks(8474),
                            Email = "Ilbilge53@hotmail.com",
                            MemberId = 1,
                            Name = "Borçul Egeli"
                        },
                        new
                        {
                            Id = 6,
                            CommentSubject = "Dolorem et ışık.",
                            CommentText = "Sevindi aliquam ekşili otobüs minima gördüm totam un consequatur adanaya. Şafak sıla iure adanaya. Accusantium quia vitae. Corporis sıradanlıktan bilgiyasayarı quis illo biber mutlu.",
                            CreatedDate = new DateTime(2026, 1, 2, 9, 31, 2, 596, DateTimeKind.Local).AddTicks(5821),
                            Email = "Alperen6@yahoo.com",
                            MemberId = 4,
                            Name = "Beker Tokgöz"
                        },
                        new
                        {
                            Id = 7,
                            CommentSubject = "Exercitationem kutusu et.",
                            CommentText = "Karşıdakine masaya consequuntur biber.",
                            CreatedDate = new DateTime(2026, 1, 8, 12, 2, 41, 720, DateTimeKind.Local).AddTicks(1882),
                            Email = "Berginsenge.Karaduman@hotmail.com",
                            MemberId = 4,
                            Name = "Çimen Adal"
                        },
                        new
                        {
                            Id = 8,
                            CommentSubject = "Aut alias sıla.",
                            CommentText = "çünkü",
                            CreatedDate = new DateTime(2026, 1, 8, 8, 24, 27, 599, DateTimeKind.Local).AddTicks(9192),
                            Email = "Karak_Egeli@hotmail.com",
                            MemberId = 10,
                            Name = "Bağa Karadaş"
                        },
                        new
                        {
                            Id = 9,
                            CommentSubject = "Salladı reprehenderit qui.",
                            CommentText = "Consectetur sunt ona gidecekmiş okuma eaque.",
                            CreatedDate = new DateTime(2026, 1, 1, 8, 25, 14, 508, DateTimeKind.Local).AddTicks(9130),
                            Email = "Aygirak_Karabulut30@gmail.com",
                            MemberId = 4,
                            Name = "Basut Yılmazer"
                        },
                        new
                        {
                            Id = 10,
                            CommentSubject = "Reprehenderit uzattı blanditiis.",
                            CommentText = "Tempora mutlu quasi telefonu incidunt layıkıyla mi.\nEos ötekinden qui sarmal molestiae consequatur sed layıkıyla çorba.\nSıradanlıktan enim adresini.\nKi yazın ullam quae ama dolayı eos.\nQuia fugit corporis aut voluptatem lambadaki gitti yaptı.\nDucimus koştum dignissimos.",
                            CreatedDate = new DateTime(2026, 1, 2, 14, 19, 36, 196, DateTimeKind.Local).AddTicks(7090),
                            Email = "Baltaci.Ekici@hotmail.com",
                            MemberId = 2,
                            Name = "Alpagut Erbulak"
                        },
                        new
                        {
                            Id = 11,
                            CommentSubject = "İure commodi teldeki.",
                            CommentText = "ışık",
                            CreatedDate = new DateTime(2026, 1, 10, 10, 37, 9, 567, DateTimeKind.Local).AddTicks(302),
                            Email = "Alper.Basoglu@gmail.com",
                            MemberId = 3,
                            Name = "Arık Arıcan"
                        },
                        new
                        {
                            Id = 12,
                            CommentSubject = "De minima commodi.",
                            CommentText = "Beğendim çorba yazın. Masanın non şafak gül nesciunt numquam dolorem. Neque veritatis adresini sit non sinema. Ratione lambadaki lakin voluptatem gül iure sayfası consequatur için ama.",
                            CreatedDate = new DateTime(2026, 1, 3, 10, 57, 11, 311, DateTimeKind.Local).AddTicks(4484),
                            Email = "Basti35@yahoo.com",
                            MemberId = 5,
                            Name = "Arıkağan Koç"
                        },
                        new
                        {
                            Id = 13,
                            CommentSubject = "Karşıdakine explicabo consequuntur.",
                            CommentText = "Aperiam dolores sinema quis ona aliquid voluptatem. Sıfat laboriosam dağılımı adipisci doğru. Koşuyorlar beğendim qui quis doloremque makinesi dışarı.",
                            CreatedDate = new DateTime(2026, 1, 4, 15, 17, 53, 768, DateTimeKind.Local).AddTicks(1579),
                            Email = "Kirgavul38@hotmail.com",
                            MemberId = 4,
                            Name = "Barlıbay Denkel"
                        },
                        new
                        {
                            Id = 14,
                            CommentSubject = "Açılmadan koştum layıkıyla.",
                            CommentText = "Ut quis sit mıknatıslı sıradanlıktan ona laboriosam aliquid ötekinden voluptatem.\nTeldeki ea quia koyun laboriosam doğru praesentium modi masanın.\nEnim ratione domates olduğu sunt cezbelendi filmini un sokaklarda bilgiyasayarı.\nBeğendim voluptatem esse uzattı masanın quis dolores rem et.",
                            CreatedDate = new DateTime(2026, 1, 10, 11, 3, 8, 947, DateTimeKind.Local).AddTicks(8769),
                            Email = "Bokde.Tuglu93@yahoo.com",
                            MemberId = 5,
                            Name = "Aygırak Tuğlu"
                        },
                        new
                        {
                            Id = 15,
                            CommentSubject = "Nemo fugit odit.",
                            CommentText = "Bilgiyasayarı dolores fugit commodi un eve iusto tempora.",
                            CreatedDate = new DateTime(2026, 1, 8, 21, 37, 35, 322, DateTimeKind.Local).AddTicks(8668),
                            Email = "Baykara.Avan@yahoo.com",
                            MemberId = 10,
                            Name = "Ağlamış Erkekli"
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Communication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Communication", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 6, 15, 54, 28, 893, DateTimeKind.Local).AddTicks(4511),
                            Email = "Dururbunsuz_Dalkiran45@gmail.com",
                            Message = "Lakin voluptatum enim quasi et. Un nisi ama öyle umut modi dolorem balıkhaneye. Patlıcan alias consequatur praesentium sit. Velit in nostrum voluptatem reprehenderit domates. Voluptatem magnam ab architecto ona nostrum ut beğendim.",
                            Name = "Bilgiç Karaer",
                            Subject = "Magnam cezbelendi."
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 6, 15, 36, 52, 833, DateTimeKind.Local).AddTicks(330),
                            Email = "Aral_Bolatli29@hotmail.com",
                            Message = "İnventore non suscipit accusantium domates voluptate modi patlıcan. Değerli ea dolore autem. Quae voluptate et sıradanlıktan voluptatum quis. Kalemi quia umut. Sit ea consequuntur veritatis dolayı. Quis corporis quia teldeki enim ve dolores sevindi ullam.",
                            Name = "Alpata Tekelioğlu",
                            Subject = "Commodi bilgisayarı."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 8, 12, 45, 2, 292, DateTimeKind.Local).AddTicks(4162),
                            Email = "Akbas.Sezek@hotmail.com",
                            Message = "Sed sit tv. Alias quaerat koşuyorlar açılmadan voluptas ipsam architecto. Amet iusto koşuyorlar.",
                            Name = "Balaban Akgül",
                            Subject = "Dicta esse."
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 7, 20, 5, 17, 239, DateTimeKind.Local).AddTicks(1318),
                            Email = "Caba_Dogan@yahoo.com",
                            Message = "Layıkıyla deleniti koşuyorlar aut alias sayfası koşuyorlar. Nihil velit iusto gitti ratione voluptatem rem. Eum sunt oldular sed nostrum layıkıyla açılmadan de. İnventore layıkıyla tv balıkhaneye bilgiyasayarı değerli voluptatem consequuntur suscipit lakin. Çıktılar sayfası doğru uzattı voluptas olduğu velit telefonu otobüs ut. Koyun gitti enim bundan koşuyorlar architecto ex eaque gidecekmiş.",
                            Name = "Ayızdağ Dağdaş",
                            Subject = "İpsam bahar."
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 10, 3, 37, 16, 407, DateTimeKind.Local).AddTicks(5095),
                            Email = "Baltur.Sezek28@hotmail.com",
                            Message = "Numquam domates amet sit lambadaki quia gitti mutlu qui anlamsız. Ut et ducimus. Otobüs dağılımı sevindi ve aperiam totam gördüm sinema sıla voluptatum. Gördüm sıla ad koştum architecto. Quia ea corporis ducimus ab qui iusto camisi. Neque bilgiyasayarı çorba ve ab molestiae odit.",
                            Name = "Asuğ Örge",
                            Subject = "Rem koyun."
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Firstame")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Members", "blg");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "58",
                            CreatedDate = new DateTime(2025, 5, 1, 7, 47, 16, 66, DateTimeKind.Local).AddTicks(3391),
                            Email = "Akibudak72@hotmail.com",
                            Firstame = "Barkdurmuş",
                            LastName = "Akan",
                            PassWord = "oKmv5SgI5Z",
                            PhoneNumber = 9827996
                        },
                        new
                        {
                            Id = 2,
                            Age = "58",
                            CreatedDate = new DateTime(2025, 2, 22, 10, 53, 15, 771, DateTimeKind.Local).AddTicks(8874),
                            Email = "Acik.Demirel@hotmail.com",
                            Firstame = "Adberilgen",
                            LastName = "Akman",
                            PassWord = "lMS9i5R3F9",
                            PhoneNumber = 3639888
                        },
                        new
                        {
                            Id = 3,
                            Age = "32",
                            CreatedDate = new DateTime(2025, 9, 15, 20, 3, 14, 130, DateTimeKind.Local).AddTicks(807),
                            Email = "Isik3@gmail.com",
                            Firstame = "Bengi",
                            LastName = "Erberk",
                            PassWord = "jFuxVHPRd2",
                            PhoneNumber = 5657393
                        },
                        new
                        {
                            Id = 4,
                            Age = "45",
                            CreatedDate = new DateTime(2025, 11, 27, 9, 58, 9, 442, DateTimeKind.Local).AddTicks(4721),
                            Email = "Alpamis_Mayhos88@gmail.com",
                            Firstame = "Kezlik",
                            LastName = "Öymen",
                            PassWord = "gDSIecwqb9",
                            PhoneNumber = 8441234
                        },
                        new
                        {
                            Id = 5,
                            Age = "33",
                            CreatedDate = new DateTime(2025, 10, 4, 4, 41, 11, 856, DateTimeKind.Local).AddTicks(2266),
                            Email = "Atasu55@yahoo.com",
                            Firstame = "Akpıra",
                            LastName = "Akyüz",
                            PassWord = "I9D930dE2F",
                            PhoneNumber = 3232194
                        },
                        new
                        {
                            Id = 6,
                            Age = "31",
                            CreatedDate = new DateTime(2025, 7, 2, 20, 24, 48, 954, DateTimeKind.Local).AddTicks(7729),
                            Email = "Askin.Eronat22@hotmail.com",
                            Firstame = "Abakan",
                            LastName = "Abadan",
                            PassWord = "xN5ycjcI56",
                            PhoneNumber = 7739958
                        },
                        new
                        {
                            Id = 7,
                            Age = "32",
                            CreatedDate = new DateTime(2025, 7, 28, 7, 19, 28, 887, DateTimeKind.Local).AddTicks(8339),
                            Email = "Gulemen6@hotmail.com",
                            Firstame = "Aydemir",
                            LastName = "Baykam",
                            PassWord = "WOKhy3gcdK",
                            PhoneNumber = 4025494
                        },
                        new
                        {
                            Id = 8,
                            Age = "47",
                            CreatedDate = new DateTime(2025, 3, 14, 6, 35, 25, 454, DateTimeKind.Local).AddTicks(4381),
                            Email = "Berkyaruk_Oraloglu57@gmail.com",
                            Firstame = "Atıkutlutaş",
                            LastName = "Dağlaroğlu",
                            PassWord = "_JqBRy4iuk",
                            PhoneNumber = 1832736
                        },
                        new
                        {
                            Id = 9,
                            Age = "63",
                            CreatedDate = new DateTime(2025, 12, 30, 19, 13, 38, 346, DateTimeKind.Local).AddTicks(2691),
                            Email = "Burulgu.Atakol95@yahoo.com",
                            Firstame = "Bökde",
                            LastName = "Tazegül",
                            PassWord = "xxo1q6p3fp",
                            PhoneNumber = 6366399
                        },
                        new
                        {
                            Id = 10,
                            Age = "30",
                            CreatedDate = new DateTime(2025, 5, 5, 19, 8, 34, 225, DateTimeKind.Local).AddTicks(9254),
                            Email = "Bengi82@gmail.com",
                            Firstame = "Eğrim",
                            LastName = "Saygıner",
                            PassWord = "R7SPmrHdLW",
                            PhoneNumber = 9540697
                        });
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Blogs", b =>
                {
                    b.HasOne("Blog.Application.Models.Entities.Admins", "Admins")
                        .WithMany("Blogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Comments", b =>
                {
                    b.HasOne("Blog.Application.Models.Entities.Members", "Members")
                        .WithMany("Comments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Admins", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Blog.Application.Models.Entities.Members", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
